In [26]:
import numpy as np


In [27]:
obj = np.array([2,4,6,8])
obj

array([2, 4, 6, 8])

In [28]:
obj1 = np.array([[1,3,5,7], [2,4,6,8]] , dtype = 'int16')


In [29]:
print(obj1)

[[1 3 5 7]
 [2 4 6 8]]


In [30]:
obj.ndim

1

In [31]:
obj1.ndim

2

In [32]:
obj1.shape

(2, 4)

In [33]:
obj1.size

8

In [34]:
import numpy as np

In [35]:
import sys

In [36]:
import time

In [37]:
S = range(1000)
print(sys.getsizeof(5)*len(S))

D = np.arange(1000)
print(D.size*D.itemsize)

28000
4000


In [38]:
obj1.dtype

dtype('int16')

In [39]:
obj1.itemsize

2

## Accessing/changing specific element ,rows ,  column etc

In [40]:
a = np.array([[1,2,3,4,5,6,7] , [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [43]:
a.shape

(2, 7)

In [44]:
a[1,2]

10

In [45]:
a[0,4]

5

In [46]:
a[: , 2]

array([ 3, 10])

In [47]:
a[0 ,1:6:2]

array([2, 4, 6])

## Array creation method

In [4]:
import numpy as np

In [5]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
np.full((2,4) , 34 ,dtype = 'float16')

array([[34., 34., 34., 34.],
       [34., 34., 34., 34.]], dtype=float16)

In [10]:
np.full_like(a.shape ,4)

NameError: name 'a' is not defined

In [12]:
np.random.rand(4,2)

array([[0.51027678, 0.227063  ],
       [0.1964304 , 0.82431933],
       [0.35385869, 0.04630374],
       [0.44344933, 0.96343616]])

In [13]:
np.random.randint(7 , size =(3,3))

array([[5, 0, 4],
       [6, 3, 5],
       [4, 6, 5]])

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
arr =np.array([1,2,3])
r1 = np.repeat(arr,4)
print(r1)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [20]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,2] = 6 
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 6.]
 [0. 0. 0.]]
